version: '3.8'

networks:
  hosting_network:
    external: true

services:
  cocktail_app:
    container_name: cocktail_app
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./build:/usr/share/nginx/html
    networks:
      - hosting_network
